// <auto-generated />
using System;
using Locadora.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocadoraAgro.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LocadoraAgro.Models.FilmeModel", b =>
                {
                    b.Property<int>("FilmeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FilmeId"));

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("FilmeId");

                    b.ToTable("Filmes");

                    b.HasData(
                        new
                        {
                            FilmeId = 1,
                            Genero = "Sci-Fi",
                            Nome = "Inception",
                            Quantidade = 10
                        },
                        new
                        {
                            FilmeId = 2,
                            Genero = "Action",
                            Nome = "The Dark Knight",
                            Quantidade = 15
                        },
                        new
                        {
                            FilmeId = 3,
                            Genero = "Sci-Fi",
                            Nome = "Interstellar",
                            Quantidade = 5
                        },
                        new
                        {
                            FilmeId = 4,
                            Genero = "Sci-Fi",
                            Nome = "The Matrix",
                            Quantidade = 8
                        },
                        new
                        {
                            FilmeId = 5,
                            Genero = "Romance",
                            Nome = "Titanic",
                            Quantidade = 20
                        },
                        new
                        {
                            FilmeId = 6,
                            Genero = "Drama",
                            Nome = "Forrest Gump",
                            Quantidade = 12
                        },
                        new
                        {
                            FilmeId = 7,
                            Genero = "Drama",
                            Nome = "The Shawshank Redemption",
                            Quantidade = 10
                        },
                        new
                        {
                            FilmeId = 8,
                            Genero = "Crime",
                            Nome = "The Godfather",
                            Quantidade = 7
                        },
                        new
                        {
                            FilmeId = 9,
                            Genero = "Crime",
                            Nome = "Pulp Fiction",
                            Quantidade = 8
                        },
                        new
                        {
                            FilmeId = 10,
                            Genero = "Sci-Fi",
                            Nome = "Avatar",
                            Quantidade = 18
                        },
                        new
                        {
                            FilmeId = 11,
                            Genero = "Action",
                            Nome = "Gladiator",
                            Quantidade = 9
                        },
                        new
                        {
                            FilmeId = 12,
                            Genero = "Animation",
                            Nome = "The Lion King",
                            Quantidade = 20
                        },
                        new
                        {
                            FilmeId = 13,
                            Genero = "Animation",
                            Nome = "Finding Nemo",
                            Quantidade = 15
                        },
                        new
                        {
                            FilmeId = 14,
                            Genero = "Animation",
                            Nome = "Frozen",
                            Quantidade = 25
                        },
                        new
                        {
                            FilmeId = 15,
                            Genero = "Sci-Fi",
                            Nome = "Star Wars: A New Hope",
                            Quantidade = 10
                        },
                        new
                        {
                            FilmeId = 16,
                            Genero = "Action",
                            Nome = "The Avengers",
                            Quantidade = 22
                        },
                        new
                        {
                            FilmeId = 17,
                            Genero = "Action",
                            Nome = "Black Panther",
                            Quantidade = 14
                        },
                        new
                        {
                            FilmeId = 18,
                            Genero = "Drama",
                            Nome = "Joker",
                            Quantidade = 0
                        },
                        new
                        {
                            FilmeId = 19,
                            Genero = "Animation",
                            Nome = "Toy Story",
                            Quantidade = 19
                        },
                        new
                        {
                            FilmeId = 20,
                            Genero = "Fantasy",
                            Nome = "The Lord of the Rings: The Fellowship of the Ring",
                            Quantidade = 10
                        });
                });

            modelBuilder.Entity("LocadoraAgro.Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin@firstpalace.com",
                            FullName = "admin",
                            Password = new byte[] { 140, 105, 118, 229, 181, 65, 4, 21, 189, 233, 8, 189, 77, 238, 21, 223, 177, 103, 169, 200, 115, 252, 75, 184, 168, 31, 111, 42, 180, 72, 169, 24 }
                        });
                });

            modelBuilder.Entity("LocadoraAgro.Models.ViewModel.ViewLocacao", b =>
                {
                    b.Property<int>("idLocacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idLocacao"));

                    b.Property<string>("Filme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locatario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataDevolucao")
                        .HasColumnType("datetime2");

                    b.HasKey("idLocacao");

                    b.ToTable("Locacao");
                });
#pragma warning restore 612, 618
        }
    }
}
